### ISSUE TITLE
3 桁以上の DecimalEscape がエラーになる

### ISSUE THREAD

**Issue by kariya-mitsuru** [onihusube/rime#2]
DecimalEscape は 3 桁以上でも使用できて、続く数字全部を飲み込みます。
例）https://wandbox.org/permlink/D4GXKWjaDVhvpsSG

例外は 0 始まりの時だけで、その場合だけ後ろに数字が続いてはいけません。
（まぁキャプチャグループ 100 個以上って普通は無いと思いますが…）

ちなみに、DecimalEscape が表す数値は、それが出現するより前（文字列の左側）のキャプチャグループ数以下じゃないといけないので（実行時例外が出る）、それもチェックできるとより良いですね。

**Comment by onihusube** [comment]
キャプチャグループの数をチェックしてエラーにするとこまで完了しました。ありがとうございました！
