### ISSUE TITLE
ClassAtomExClass 等の開始文字と終了文字が合わないケースがエラーにならない

### ISSUE THREAD

**Issue by kariya-mitsuru** [onihusube/rime#6]
*ClassAtomExClass* 等で、例えば `[[:upper.]]` とした場合、どうも GCC や Clang ではエラーになるようですが、rime ではエラーとならずに見逃されるため、実行時エラーが発生してしまいます。

余談ですが、個人的には、`[:upper.` の時点で *ClassAtomExClass*、*ClassAtomCollatingElement*、*ClassAtomEquivalence* のいずれの生成規則にもマッチしないので、全ての文字がそれぞれ独立した *ClassAtomNoDash* として解釈されるべきだと思うのですが、世の中的にはどうもそのような解釈にはなっていないようです。

**Comment by onihusube** [comment]
GCC/calngに合わせる（POSIXクラスとしてパースできない場合にエラーとする）ようにしました、ありがとうございます！
