### ISSUE TITLE
ClassRanges で開始文字より終了文字の方が小さいケースがエラーにならない

### ISSUE THREAD

**Issue by kariya-mitsuru** [onihusube/rime#7]
*ClassRanges* で、例えば `[z-a]` のように開始文字の文字コードより終了文字の文字コードの方が小さい場合にはエラーと規定されていますが、rime ではエラーにならずに実行時エラーが発生してしまいます。

**Comment by onihusube** [comment]
完了しました。ご報告ありがとうございました！
