### ISSUE TITLE
QuantifierPrefix で最小繰り返し数が最大繰り返し数より大きいケースがエラーにならない

### ISSUE THREAD

**Issue by kariya-mitsuru** [onihusube/rime#8]
*QuantifierPrefix* で、例えば `{1,0}` のように最小繰り返し数が最大繰り返し数より大きいケースはエラーと規定されていますが、rime ではエラーにならずに実行時エラーが発生してしまいます。

**Comment by onihusube** [comment]
修正しました、ご報告ありがとうございます！
